export const endpoints = {
  health: () => '/health',
  me: () => '/me',
  stat: () => '/stat',
  statActions: () => '/stat/actions',
  signup: () => '/signup',
  signin: () => '/signin',
  forgotPassword: () => '/forgot-password',
  verifyResetCode: () => '/verify-reset-code',
  resetPassword: () => '/reset-password',
  settingsTokens: () => '/settings/tokens',
  settingsTokenById: (tokenId: string) => `/settings/tokens/${tokenId}`,
  teams: () => '/teams',
  teamById: (teamId: string) => `/teams/${teamId}`,
  teamProjects: (teamId: string) => `/teams/${teamId}/projects`,
  teamMembers: (teamId: string) => `/teams/${teamId}/members`,
  teamMemberByUser: (teamId: string, userId: string) => `/teams/${teamId}/members/${userId}`,
  teamInvites: (teamId: string) => `/teams/${teamId}/invites`,
  teamInviteById: (teamId: string, inviteId: string) => `/teams/${teamId}/invites/${inviteId}`,
  teamInvite: (teamId: string) => `/teams/${teamId}/invite`,
  teamInviteByToken: (token: string) => `/team-invites/${token}`,
  teamInviteAccept: (token: string) => `/team-invites/${token}/accept`,
  projects: () => '/projects',
  projectById: (projectId: string) => `/projects/${projectId}`,
  directions: (projectId: string) => `/projects/${projectId}/directions`,
  stages: (projectId: string) => `/projects/${projectId}/stages`,
  stageById: (projectId: string, stageId: string) => `/projects/${projectId}/stages/${stageId}`,
  tasks: (projectId: string, stageId: string) => `/projects/${projectId}/stages/${stageId}/tasks`,
  toggleTask: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}/toggle`,
  editTaskTitle: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}/title`,
  assignTask: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}/assign`,
  patchTaskMeta: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}/meta`,
  deleteTask: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}`,
  projectTasks: (projectId: string) => `/projects/${projectId}/tasks`,
  toggleProjectTask: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}/toggle`,
  editProjectTaskTitle: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}/title`,
  assignProjectTask: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}/assign`,
  patchProjectTaskMeta: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}/meta`,
  deleteProjectTask: (projectId: string, taskId: string) => `/projects/${projectId}/tasks/${taskId}`,
  agentRuns: (projectId: string) => `/projects/${projectId}/agent/runs`,
  agentRunById: (projectId: string, runId: string) => `/projects/${projectId}/agent/runs/${runId}`,
  shareLink: (projectId: string) => `/projects/${projectId}/share-link`,
  requestReview: (projectId: string, stageId: string) =>
    `/projects/${projectId}/stages/${stageId}/request-review`,
  publicProject: (shareToken: string) => `/p/${shareToken}`,
  approvePublicProject: (shareToken: string) => `/p/${shareToken}/approve`,
  githubInstallations: () => '/github/installations',
  githubInstallationRepos: (installationId: string) => `/github/installations/${installationId}/repos`,
  githubCallbackInstall: () => '/github/callback/install',
  projectRepositories: (projectId: string) => `/projects/${projectId}/repositories`,
  projectRepositoryById: (projectId: string, repoId: string) => `/projects/${projectId}/repositories/${repoId}`,
  webhookEvents: (projectId: string) => `/projects/${projectId}/webhook-events`,
  meTelegram: () => '/me/telegram',
  meTelegramConnectLink: () => '/me/telegram/connect-link',
  projectTelegramBindings: (projectId: string) => `/projects/${projectId}/telegram/bindings`,
  projectTelegramBindingById: (projectId: string, bindingId: string) =>
    `/projects/${projectId}/telegram/bindings/${bindingId}`,
  projectTelegramBindToken: (projectId: string) => `/projects/${projectId}/telegram/bind-token`,
};
