export const endpoints = {
  health: () => '/health',
  me: () => '/me',
  stat: () => '/stat',
  signup: () => '/signup',
  signin: () => '/signin',
  forgotPassword: () => '/forgot-password',
  verifyResetCode: () => '/verify-reset-code',
  resetPassword: () => '/reset-password',
  teams: () => '/teams',
  teamById: (teamId: string) => `/teams/${teamId}`,
  teamProjects: (teamId: string) => `/teams/${teamId}/projects`,
  teamMembers: (teamId: string) => `/teams/${teamId}/members`,
  teamMemberByUser: (teamId: string, userId: string) => `/teams/${teamId}/members/${userId}`,
  teamInvites: (teamId: string) => `/teams/${teamId}/invites`,
  teamInviteById: (teamId: string, inviteId: string) => `/teams/${teamId}/invites/${inviteId}`,
  teamInvite: (teamId: string) => `/teams/${teamId}/invite`,
  teamInviteByToken: (token: string) => `/team-invites/${token}`,
  teamInviteAccept: (token: string) => `/team-invites/${token}/accept`,
  projects: () => '/projects',
  projectById: (projectId: string) => `/projects/${projectId}`,
  stages: (projectId: string) => `/projects/${projectId}/stages`,
  stageById: (projectId: string, stageId: string) => `/projects/${projectId}/stages/${stageId}`,
  tasks: (projectId: string, stageId: string) => `/projects/${projectId}/stages/${stageId}/tasks`,
  toggleTask: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}/toggle`,
  editTaskTitle: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}/title`,
  deleteTask: (projectId: string, stageId: string, taskId: string) =>
    `/projects/${projectId}/stages/${stageId}/tasks/${taskId}`,
  shareLink: (projectId: string) => `/projects/${projectId}/share-link`,
  requestReview: (projectId: string, stageId: string) =>
    `/projects/${projectId}/stages/${stageId}/request-review`,
  publicProject: (shareToken: string) => `/p/${shareToken}`,
  approvePublicProject: (shareToken: string) => `/p/${shareToken}/approve`,
};
